### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by giers10** [Rakosi/shadow-removal#1]
Hi,
I'm trying to get your script running on my system, unfortunately I don't know which versions of Python / OpenCV / other dependencies is required. Could you give some advice on that? Thank you.
- Found out it has to be OpenCV 3+ because OpenCV 2 depends on Numpy < 1.10, which doesn't have np.cbrt, which the script uses

**Comment by giers10** [comment]
Got it running with Python 2.7.15, OpenCV 3.1, Numpy 1.12.1, SciKit-Image 0.13.1.
Verbose Mode doesn't work but that seems to be an issue with my OpenCV installation, not a real issue.

**Comment by YalimD** [comment]
pr1est0r,

Thank you for your feedback. I will add the dependency info soon.
