### ISSUE TITLE
Algorithm not working properly

### ISSUE THREAD

**Issue by SuperbTUM** [Rakosi/shadow-removal#2]
Hi YalimD. I tested your code with my [image](https://drive.google.com/file/d/1my0a9iWL1kHazQw5f2cmzhzt1ZNhxYjg/view?usp=sharing) but it is not working. The result looks like [this](https://drive.google.com/file/d/16aj1-z7pVwSBMkaqzUIy8zutGmG_iI5x/view?usp=sharing). Not knowing why... Thanks in advance!

**Comment by YalimD** [comment]
Hi  @SuperbTUM,

Sorry for the late reply.

I tested the image you have shared and noticed that the colors are read wrong by OpenCV. The algorithm expects the image to be in BGR, not RGB. 

If you, for instance, convert the image using 

`cv.cvtColor(img, cv.COLOR_RGB2BGR) `

before passing it to the `remove_shadows` function, the result is below. You can adjust parameters to make it better.

![image](https://user-images.githubusercontent.com/6225703/154842339-e38aa7db-3bb5-430b-bd63-3632e23820b5.png)

You can now test it on the [notebook](https://github.com/YalimD/image_shadow_remover/blob/43f9e02c6c87ad47437a80a3f6c38d3b66c0c5fa/Shadow_Demo.ipynb) I uploaded as well.

Hope it helps
